//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FES__File_Encryption_Software_.Resources.Languages.LoginForm {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LoginFormLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoginFormLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FES__File_Encryption_Software_.Resources.Languages.LoginForm.LoginFormLang", typeof(LoginFormLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password is in invalid format! Supported format is: [a-zA-Z0-9] Supported lenght is 5-20 letters.
        /// </summary>
        public static string invalidFormatP {
            get {
                return ResourceManager.GetString("invalidFormatP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format.
        /// </summary>
        public static string invalidFormatT {
            get {
                return ResourceManager.GetString("invalidFormatT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username is in invalid format! Supported format is: [a-zA-Z][a-zA-Z0-9] Supported lenght is 5-20 letters.
        /// </summary>
        public static string invalidFormatU {
            get {
                return ResourceManager.GetString("invalidFormatU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string loginBtn {
            get {
                return ResourceManager.GetString("loginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successfully logged in!.
        /// </summary>
        public static string loginS {
            get {
                return ResourceManager.GetString("loginS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successful.
        /// </summary>
        public static string loginST {
            get {
                return ResourceManager.GetString("loginST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered username or password is wrong!.
        /// </summary>
        public static string loginUS {
            get {
                return ResourceManager.GetString("loginUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login unsuccessful.
        /// </summary>
        public static string loginUST {
            get {
                return ResourceManager.GetString("loginUST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string passwordLabel {
            get {
                return ResourceManager.GetString("passwordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string registerBtn {
            get {
                return ResourceManager.GetString("registerBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration was successful! Now login with your new account..
        /// </summary>
        public static string registerS {
            get {
                return ResourceManager.GetString("registerS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration successful.
        /// </summary>
        public static string registerST {
            get {
                return ResourceManager.GetString("registerST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration was unsuccessful! [Username might be already taken / Address already registered] Please try it again later..
        /// </summary>
        public static string registerUS {
            get {
                return ResourceManager.GetString("registerUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration unsuccessful.
        /// </summary>
        public static string registerUST {
            get {
                return ResourceManager.GetString("registerUST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember password.
        /// </summary>
        public static string rememberCheck {
            get {
                return ResourceManager.GetString("rememberCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string usernameLabel {
            get {
                return ResourceManager.GetString("usernameLabel", resourceCulture);
            }
        }
    }
}
