//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FES__File_Encryption_Software_.Resources.Languages.MainForm {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainFormLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainFormLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FES__File_Encryption_Software_.Resources.Languages.MainForm.MainFormLang", typeof(MainFormLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;- Decrypt.
        /// </summary>
        public static string btnDecrypt {
            get {
                return ResourceManager.GetString("btnDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt -&gt;.
        /// </summary>
        public static string btnEncrypt {
            get {
                return ResourceManager.GetString("btnEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools and Settings.
        /// </summary>
        public static string btnHelp {
            get {
                return ResourceManager.GetString("btnHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder selection.
        /// </summary>
        public static string btnLDirectory {
            get {
                return ResourceManager.GetString("btnLDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log-out.
        /// </summary>
        public static string btnLogout {
            get {
                return ResourceManager.GetString("btnLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string btnRefresh {
            get {
                return ResourceManager.GetString("btnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset key.
        /// </summary>
        public static string btnReset {
            get {
                return ResourceManager.GetString("btnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset encryption key? [YOU WILL BE UNABLE TO DECRYPT FILES ENCRYPTED WITH PREVIOUS KEY].
        /// </summary>
        public static string btnResetQ {
            get {
                return ResourceManager.GetString("btnResetQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption key reset.
        /// </summary>
        public static string btnResetT {
            get {
                return ResourceManager.GetString("btnResetT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set key.
        /// </summary>
        public static string btnSet {
            get {
                return ResourceManager.GetString("btnSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show key.
        /// </summary>
        public static string btnShow {
            get {
                return ResourceManager.GetString("btnShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted files:.
        /// </summary>
        public static string efLabel {
            get {
                return ResourceManager.GetString("efLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid CrypKey!.
        /// </summary>
        public static string errorLabel0C {
            get {
                return ResourceManager.GetString("errorLabel0C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation terminated.
        /// </summary>
        public static string errorLabel0D {
            get {
                return ResourceManager.GetString("errorLabel0D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to exit.
        /// </summary>
        public static string errorLabel0E {
            get {
                return ResourceManager.GetString("errorLabel0E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file!.
        /// </summary>
        public static string errorLabel0F {
            get {
                return ResourceManager.GetString("errorLabel0F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected exception.
        /// </summary>
        public static string errorLabel0R {
            get {
                return ResourceManager.GetString("errorLabel0R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exists!.
        /// </summary>
        public static string errorLabel1F {
            get {
                return ResourceManager.GetString("errorLabel1F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files with the same name cannot be together in a single Drag and Drop action..
        /// </summary>
        public static string errorMsg0D {
            get {
                return ResourceManager.GetString("errorMsg0D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background task is currently in progress!.
        /// </summary>
        public static string errorMsg0E {
            get {
                return ResourceManager.GetString("errorMsg0E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your key was reseted due to an unexpected exception. We apologize..
        /// </summary>
        public static string errorMsg0R {
            get {
                return ResourceManager.GetString("errorMsg0R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-encrypted files:.
        /// </summary>
        public static string nefLabel {
            get {
                return ResourceManager.GetString("nefLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key is in wrong format, must be a Base64 string with 44 chars. (Rather use keys generated only by this application.).
        /// </summary>
        public static string setKeyError {
            get {
                return ResourceManager.GetString("setKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new AES key:.
        /// </summary>
        public static string setKeyLabel {
            get {
                return ResourceManager.GetString("setKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong format.
        /// </summary>
        public static string setKeyQT {
            get {
                return ResourceManager.GetString("setKeyQT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set key.
        /// </summary>
        public static string setKeyTitle {
            get {
                return ResourceManager.GetString("setKeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied!.
        /// </summary>
        public static string showKeyCC {
            get {
                return ResourceManager.GetString("showKeyCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string showKeyCCBtn {
            get {
                return ResourceManager.GetString("showKeyCCBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key:.
        /// </summary>
        public static string showKeyKLabel {
            get {
                return ResourceManager.GetString("showKeyKLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenght:.
        /// </summary>
        public static string showKeyLLabel {
            get {
                return ResourceManager.GetString("showKeyLLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show key.
        /// </summary>
        public static string showKeyTitle {
            get {
                return ResourceManager.GetString("showKeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User:.
        /// </summary>
        public static string usernameLabel {
            get {
                return ResourceManager.GetString("usernameLabel", resourceCulture);
            }
        }
    }
}
