//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FES__File_Encryption_Software_.Resources.Languages.HelpDialog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HelpDialogLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpDialogLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FES__File_Encryption_Software_.Resources.Languages.HelpDialog.HelpDialogLang", typeof(HelpDialogLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        public static string pAccountDeleteBtn {
            get {
                return ResourceManager.GetString("pAccountDeleteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown exception has occured while deleting your account..
        /// </summary>
        public static string pAccountDeleteE {
            get {
                return ResourceManager.GetString("pAccountDeleteE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete your account? (Make sure to backup your encryption key).
        /// </summary>
        public static string pAccountDeleteQ {
            get {
                return ResourceManager.GetString("pAccountDeleteQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been successfully deleted..
        /// </summary>
        public static string pAccountDeleteS {
            get {
                return ResourceManager.GetString("pAccountDeleteS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account delete.
        /// </summary>
        public static string pAccountDeleteT {
            get {
                return ResourceManager.GetString("pAccountDeleteT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string pAccountLabel {
            get {
                return ResourceManager.GetString("pAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password:.
        /// </summary>
        public static string pChangePLabel {
            get {
                return ResourceManager.GetString("pChangePLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string pChangeUBtn {
            get {
                return ResourceManager.GetString("pChangeUBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change username:.
        /// </summary>
        public static string pChangeULabel {
            get {
                return ResourceManager.GetString("pChangeULabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current username:.
        /// </summary>
        public static string pCurrentULabel {
            get {
                return ResourceManager.GetString("pCurrentULabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been successfully changed. Please log-in again..
        /// </summary>
        public static string pPasswordChanged {
            get {
                return ResourceManager.GetString("pPasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown exception has occured while changing your password..
        /// </summary>
        public static string pPasswordE {
            get {
                return ResourceManager.GetString("pPasswordE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string pPasswordLabel {
            get {
                return ResourceManager.GetString("pPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string pPasswordT {
            get {
                return ResourceManager.GetString("pPasswordT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username has been successfully changed to &apos;.
        /// </summary>
        public static string pUsernameChanged {
            get {
                return ResourceManager.GetString("pUsernameChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string pUsernameLabel {
            get {
                return ResourceManager.GetString("pUsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change username.
        /// </summary>
        public static string pUsernameT {
            get {
                return ResourceManager.GetString("pUsernameT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is already taken..
        /// </summary>
        public static string pUsernameTaken {
            get {
                return ResourceManager.GetString("pUsernameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be aware that setting the buffer to a custom size can have negative impact on the program behaviour..
        /// </summary>
        public static string sBufferChange {
            get {
                return ResourceManager.GetString("sBufferChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer size.
        /// </summary>
        public static string sBufferLabel {
            get {
                return ResourceManager.GetString("sBufferLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings change.
        /// </summary>
        public static string sChangeT {
            get {
                return ResourceManager.GetString("sChangeT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string sConfigLabel {
            get {
                return ResourceManager.GetString("sConfigLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string sDeleteBtn {
            get {
                return ResourceManager.GetString("sDeleteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown exception has occured while deleting your settings..
        /// </summary>
        public static string sDeleteE {
            get {
                return ResourceManager.GetString("sDeleteE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete application&apos;s settings folder. Are you sure?.
        /// </summary>
        public static string sDeleteQ {
            get {
                return ResourceManager.GetString("sDeleteQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File description.
        /// </summary>
        public static string sDescCheckBox {
            get {
                return ResourceManager.GetString("sDescCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow drop.
        /// </summary>
        public static string sDropCheckBox {
            get {
                return ResourceManager.GetString("sDropCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string sLangApplyBtn {
            get {
                return ResourceManager.GetString("sLangApplyBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string sLangLabel {
            get {
                return ResourceManager.GetString("sLangLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string sResetBtn {
            get {
                return ResourceManager.GetString("sResetBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown exception has occured while reseting your settings..
        /// </summary>
        public static string sResetE {
            get {
                return ResourceManager.GetString("sResetE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will reset all application&apos;s settings into default values. Are you sure?.
        /// </summary>
        public static string sResetQ {
            get {
                return ResourceManager.GetString("sResetQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart for new settings to take effect..
        /// </summary>
        public static string sRestartQ {
            get {
                return ResourceManager.GetString("sRestartQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About | Help.
        /// </summary>
        public static string SSAbout {
            get {
                return ResourceManager.GetString("SSAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string SSAccount {
            get {
                return ResourceManager.GetString("SSAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SSSettings {
            get {
                return ResourceManager.GetString("SSSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools and Settings.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
    }
}
